name: Regenerate dist/index.js

on:
  push:

jobs:
  regenerate_dist-index_js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: regenerate dist/index.js
      run: |
        sudo npm i -g @vercel/ncc
        npm install
        ncc build index.js

    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: dist/index.js
        commit_message: Regenerate dist/index.js
