name: Test

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          macos: echo "Hi from macos"
          linux: |
            echo "Hi from linux"
            echo "Hi from linux second line"
          windows: echo "Hi from windows"
          windowsShell: cmd

      - uses: ./
        with:
          macos: echo "test2"
          linux: echo "test2"
          windows: echo "test2"
          windowsShell: cmd

      - uses: Madrona-Games/os-specific-run@main
        with:
          macos: echo "Hi from macos"
          linux: |
            echo "Hi from linux"
            echo "Hi from linux second line"
          windows: echo "Hi from windows"

      - uses: Madrona-Games/os-specific-run@main
        with:
          macos: echo "test2"
          linux: echo "test2"
          windows: echo "test2"
          windowsShell: cmd
